name: Build basic job demo

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  ech-vars-and-secrets:
    name: 1 - Ech0 Variables and Secerts
    runs-on: ubuntu-latest
    environment: development
    env:
      MY_VARIABLE: ${{vars.MY_VARIABLE}}
      My_SECRET: ${{secrets.My_SECRET}}
    steps:
      -name: Echo repository variable
      -run: echo "MY_VARIABLE= $MY_VARIABLE"

      -name: Echo repository secret (value of this is marked as *** in logs)
      -run: echo "My_SECRET= $My_SECRET"
